//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[sea_orm(table_name = "page")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub video_id: i32,
    pub cid: i64,
    pub pid: i32,
    pub name: String,
    pub width: Option<u32>,
    pub height: Option<u32>,
    pub duration: u32,
    pub path: Option<String>,
    pub file_size_bytes: Option<i64>,
    pub video_stream_size_bytes: Option<i64>,
    pub audio_stream_size_bytes: Option<i64>,
    pub image: Option<String>,
    pub download_status: u32,
    /// SponsorBlock cut outcome code (disabled/none/cut/...) for UI
    pub sponsor_cut_result: Option<String>,
    pub created_at: String,
    pub play_video_streams: Option<String>,
    pub play_audio_streams: Option<String>,
    pub play_subtitle_streams: Option<String>,
    pub play_streams_updated_at: Option<String>,
    pub danmaku_last_synced_at: Option<String>,
    #[sea_orm(default_value = "0")]
    pub danmaku_sync_generation: u32,
    pub danmaku_cid_snapshot: Option<i64>,
    #[sea_orm(default_value = "0")]
    pub danmaku_last_write_count: u32,
    /// 是否已被 AI 重命名
    #[sea_orm(default_value = "0")]
    pub ai_renamed: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::video::Entity",
        from = "Column::VideoId",
        to = "super::video::Column::Id"
    )]
    Video,
}

impl Related<super::video::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Video.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
